 
version: '3.7'
services:
  rabbittest:
    build:
      context: .
    ports:
      - 5000:5000
    environment: 
      - AMQP_HOST: ${AMQP_HOST}
      - QUEUE_NAME: ${QUEUE_NAME}
    command: node consumer.js